
POST http://localhost:3003/login/
Content-Type: application/json

{
  "username": "christopher_phillips",
  "password": "christy@123"
}
###

GET http://localhost:3003/states/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwMjIxNjQ5fQ.zUPZzhoSbBeKw5_z70Z5U0MbgAwo9qQlULph4T7p3Bo
###

GET http://localhost:3003/states/8/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwMjIxNjQ5fQ.zUPZzhoSbBeKw5_z70Z5U0MbgAwo9qQlULph4T7p3Bo
###

POST http://localhost:3003/districts/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwMjIxNjQ5fQ.zUPZzhoSbBeKw5_z70Z5U0MbgAwo9qQlULph4T7p3Bo
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}
###

GET http://localhost:3003/districts/322/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwMjIxNjQ5fQ.zUPZzhoSbBeKw5_z70Z5U0MbgAwo9qQlULph4T7p3Bo
###

DELETE http://localhost:3003/districts/766/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwMjIxNjQ5fQ.zUPZzhoSbBeKw5_z70Z5U0MbgAwo9qQlULph4T7p3Bo
###

PUT http://localhost:3003/districts/765/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwMjIxNjQ5fQ.zUPZzhoSbBeKw5_z70Z5U0MbgAwo9qQlULph4T7p3Bo
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}
###

GET http://localhost:3003/states/5/stats/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNjkwMjIxNjQ5fQ.zUPZzhoSbBeKw5_z70Z5U0MbgAwo9qQlULph4T7p3Bo
